#!/bin/zsh

command=$1
parameter=$2
function test() {
	g++ $parameter 0_pre.o -std=c++11 -o main
	./main
}

function new() {
	leetcode show -gx -l cpp $parameter
}

function help() {
	echo "engine [command]"
	echo ""
	echo "commands:"
	echo "  engine new  [problem number]"
	echo "  engine test [filename]"
}

case $command in
	(test)
		test
		;;
	(new)
		new
		;;
	(help)
		help
		;;
	(*)
		echo "Wrong command. Try help instead."
		;;
esac